import type { Metadata } from "next";
import "../../../styles/globals.css";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="grid min-h-screen grid-cols-2 place-content-center justify-items-center gap-y-6  md:px-[100px]">
      <div className="relative col-span-2 h-[80px] w-[200px] md:col-span-1 md:w-full md:place-self-center lg:h-full lg:w-[350px]">
        <Image
          src="./fidooo-logo.svg"
          alt="fidooo logo"
          priority
          fill
          sizes="100vw"
          className="object-contain"
        />
      </div>

      <section className="col-span-2 rounded-30 bg-secondary-purple p-[40px] md:col-span-1 md:p-[80px]">
        {children}
      </section>
    </main>
  );
}
